### ISSUE TITLE
TensorFlow_Tut_3_Object_Detection_Walk-through - 3_Train.py

### ISSUE THREAD

**Issue by Setareh123** [MicrocontrollersAndMore/TensorFlow_Tut_3_Object_Detection_Walk-through#4]
Hi; 
I have followed the steps from the beginning but in running 3_train.py I get several errors! of course, by commenting    #  tf.app.run() the code is running successfully but this is not the deal!

The errors are lited below: 

C:\Users\Setareh\AppData\Local\Programs\Python\Python36\python.exe C:/Users/Setareh/Documents/TensorFlow-examples/TensorFlow_Tut_3_Object_Detection_Walk-through/3_train.py
starting program . . .
Traceback (most recent call last):
  File "C:/Users/Setareh/Documents/TensorFlow-examples/TensorFlow_Tut_3_Object_Detection_Walk-through/3_train.py", line 153, in <module>
    tf.app.run()
  File "C:\Users\Setareh\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:/Users/Setareh/Documents/TensorFlow-examples/TensorFlow_Tut_3_Object_Detection_Walk-through/3_train.py", line 115, in main
    CLONE_ON_CPU, ps_tasks, worker_job_name, is_chief, TRAINING_DATA_DIR)
  File "C:\TensorFlow\models\research\object_detection\trainer.py", line 240, in train
    detection_model = create_model_fn()
  File "C:\TensorFlow\models\research\object_detection\builders\model_builder.py", line 98, in build
    add_background_class)
  File "C:\TensorFlow\models\research\object_detection\builders\model_builder.py", line 166, in _build_ssd_model
    is_training=is_training)
  File "C:\TensorFlow\models\research\object_detection\builders\model_builder.py", line 138, in _build_ssd_feature_extractor
    override_base_feature_extractor_hyperparams)
  File "C:\TensorFlow\models\research\object_detection\models\ssd_inception_v2_feature_extractor.py", line 68, in __init__
    raise ValueError('SSD Inception V2 feature extractor always uses'
ValueError: SSD Inception V2 feature extractor always usesscope returned by `conv_hyperparams_fn` for both the base feature extractor and the additional layers added since there is no arg_scope defined for the base feature extractor.

Process finished with exit code 1
![untitled](https://user-images.githubusercontent.com/39617031/40540639-1fe8b9da-6019-11e8-9518-4b8233a22d08.jpg)

**Comment by MicrocontrollersAndMore** [comment]
Did you try the fix from this issue:

https://github.com/MicrocontrollersAndMore/TensorFlow_Tut_3_Object_Detection_Walk-through/issues/3

Due to some change Google has made recently which I haven't yet had the time to properly work out, you have to comment out some lines in ssd_inception_v2_feature_extractor.py.  I also included a note to this effect in the video comments.  I'm going to close this at this time since it's the same error and I suspect this will resolve the concern.

**Comment by AekkaratKongsuk** [comment]
I have followed the steps from the beginning but in running 3_train.py I get several errors!
How to fix ?

**Comment by sellinge** [comment]
In line 68 i changed the dataset_util to dataset_builder
train.py runs now
def get_next(config):
        return **dataset_builder**.make_initializable_iterator(dataset_builder.build(config)).get_next()

**Comment by AekkaratKongsuk** [comment]
![image](https://user-images.githubusercontent.com/31691206/42457291-502f0948-83c1-11e8-8a9a-c99f3cd2458d.png)
How to fix ?  please...

**Comment by roshankumarbhuyan** [comment]
This [Commit](https://github.com/developmentseed/label-maker/commit/94f1863945c47e1b69fe0d6d575caa0b42aa8d63) solves the Issue
